package com.smartprocessrefusao.erprefusao.enumerados;

public enum EmployeePosition {
	ANALISTA_ADMINISTRATIVO,
	AUXILIAR_ADMINISTRATIVO,
	AUXILIAR_ADMINISTRATIVO_APRENDIZ,
	AUXILIAR_DE_EXPEDIÇÃO,
	AUXILIAR_DE_PRODUÇÃO,
	COMPRADOR,
	ELETROMECÂNICO_DE_MANUTENÇÃO_INDUSTRIAL_SÊNIOR,
	FAXINEIRO,
	GERENTE_INDUSTRIAL,
	LÍDER_DE_TURNO,
	MECANICO_DE_EMPILHADEIRA,
	MOTORISTA,
	MOTORISTA_CARRETEIRO,
	OPERADOR_DE_EMPILHADEIRA,
	OPERADOR_DE_EXPEDIÇÃO,
	OPERADOR_DE_FORNO,
	OPERADOR_DE_MÁQUINA_VDC,
	SUPERVISOR_ADMINISTRATIVO,
	SUPERVISOR_DE_EXPEDIÇÃO,
	SUPERVISOR_DE_MANUTENÇÃO,
	SUPERVISOR_DE_PROCESSOS,
	SUPERVISOR_DE_SGI,
	TÉCNICO_DE_MANUTENÇÃO_ELETROMECÂNICA_PLENO
}
